# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: timetable, action: homepage }

signin:
    url: /prihlasit
    param: { module: user, action: signin }

signout:
    url: /odhlasit
    param: { module: user, action: signout }

terms_of_use:
    url: /podmienky-pouzivania
    class: sfRequestRoute
    param: { module: about, action: termsOfUse }
    requirements: {sf_method: get}

# zobrazenie vsetkych hodin
lesson_list_all:
    url: /hodina
    param: { module: lesson, action: index }

lesson_search_all:
    url: /hodina/hladat
    param: { module: lesson, action: query }

timetable_show:
    url: /moj/rozvrh/:id.:sf_format
    param: { module: timetable, action: show, sf_format: html }
    requirements:
        id: \d+
        sf_format: (?:html|txt|csv|ics|xml|list)

timetable_show_published:
    url: /rozvrh/:slug.:sf_format
    class: sfDoctrineRoute
    options: { model: UserTimetable, type: object }
    param: { module: timetablePublished, action: show, sf_format: html }
    requirements:
        #slug: \[a-z-\]+
        sf_format: (?:html|txt|csv|ics|xml|list)
        sf_method: [get, post]

timetable_new:
    url: /moj/rozvrh/novy
    param: { module: timetable, action: new }

timetable_create:
    url: /moj/rozvrh
    param: { module: timetable, action: create }
    requirements:
        sf_method: post

timetable_change_lessons:
    url: /moj/rozvrh/:id/zmenit_hodiny
    param: { module: timetable, action: changeLessons }
    requirements:
        sf_method: post

timetable_lesson_action:
    url: /moj/rozvrh/:id/akcia_hodiny
    param: { module: timetable, action: lessonAction }
    requirements:
        sf_method: post

timetable_duplicate:
    url: /moj/rozvrh/:id/duplikovat
    param: { module: timetable, action: duplicate }
    requirements:
        sf_method: post

timetable_duplicate_published:
    url: /rozvrh/:slug/duplikovat
    class: sfDoctrineRoute
    options: { model: UserTimetable, type: object }
    param: { module: timetablePublished, action: duplicate }

timetable_save:
    url: /moj/rozvrh/:id/ulozit
    param: { module: timetable, action: save }

timetable_delete:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/zmazat
    param: { module: timetable, action: deleteAsk }
    requirements: { sf_method: get }

timetable_delete_do:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/zmazat
    param: { module: timetable, action: delete }
    requirements: { sf_method: post }

timetable_import:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/importovat
    param: { module: timetable, action: import }
    requirements: { sf_method: get }

timetable_importDo:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/importovat
    param: { module: timetable, action: importDo }
    requirements: { sf_method: post }

timetable_export:
    url: /moj/rozvrh/:id/exportovat
    param: { module: timetable, action: export }

timetable_export_published:
    url: /rozvrh/:slug/exportovat
    class: sfDoctrineRoute
    options: { model: UserTimetable, type: object }
    param: { module: timetablePublished, action: export }

timetable_publish_do:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/zdielat
    param: { module: timetable, action: publishExecute }
    requirements: { sf_method: post }

timetable_unpublish_do:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/nezdielat
    param: { module: timetable, action: unpublishExecute }


timetable_publish:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/zdielat
    param: { module: timetable, action: publish }
    requirements: { sf_method: get }

timetable_unpublish:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/nezdielat
    param: { module: timetable, action: unpublish }

timetable_rename:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/premenovat
    param: { module: timetable, action: rename }
    requirements: { sf_method: get }

timetable_rename_do:
    class: sfRequestRoute
    url: /moj/rozvrh/:id/premenovat
    param: { module: timetable, action: renameExecute }
    requirements: { sf_method: post }

timetable_teacher_list:
    url: /ucitelia
    param: { module: timetableTeacher, action: list }

timetable_teacher_show:
    url: /ucitelia/:slug_or_login_or_id.:sf_format
    class: ColumnOrIdRoute
    options: { model: Teacher, type: object, column: [slug, login] }
    param: { module: timetableTeacher, action: show, sf_format: html }
    requirements:
        sf_format: (?:html|txt|csv|ics|xml|list)
        sf_method: [get, post]

timetable_teacher_export:
    url: /ucitelia/:slug_or_login_or_id/rozvrh/exportovat
    class: ColumnOrIdRoute
    options: { model: Teacher, type: object, column: [slug, login] }
    param: { module: timetableTeacher, action: export }

timetable_teacher_duplicate:
    url: /ucitelia/:slug_or_login_or_id/rozvrh/duplikovat
    class: ColumnOrIdRoute
    options: { model: Teacher, type: object, column: [slug, login] }
    param: { module: timetableTeacher, action: duplicate }

room_list:
    url: /miestnosti
    param: { module: room, action: list }

room_show:
    url: /miestnosti/:name_or_id.:sf_format
    class: ColumnOrIdRoute
    options: { model: Room, type: object, column: name }
    param: { module: room, action: show, sf_format: html }
    requirements:
        sf_format: (?:html|txt|csv|ics|xml|list)
        sf_method: [get, post]

room_timetable_export:
    url: /miestnosti/:name_or_id/rozvrh/exportovat
    class: ColumnOrIdRoute
    options: { model: Room, type: object, column: name }
    param: { module: room, action: export }

room_timetable_duplicate:
    url: /miestnosti/:name_or_id/rozvrh/duplikovat
    class: ColumnOrIdRoute
    options: { model: Room, type: object, column: name }
    param: { module: room, action: duplicate }
    
studentGroup_list:
    url: /kruzky
    param: { module: studentGroup, action: list }

studentGroup_show:
    url: /kruzky/:name_or_id.:sf_format
    class: ColumnOrIdRoute
    options: { model: StudentGroup, type: object, column: name }
    param: { module: studentGroup, action: show, sf_format: html }
    requirements:
        sf_format: (?:html|txt|csv|ics|xml|list)
        sf_method: [get, post]

studentGroup_timetable_export:
    url: /kruzky/:name_or_id/rozvrh/exportovat
    class: ColumnOrIdRoute
    options: { model: StudentGroup, type: object, column: name }
    param: { module: studentGroup, action: export }

studentGroup_timetable_duplicate:
    url: /kruzky/:name_or_id/rozvrh/duplikovat
    class: ColumnOrIdRoute
    options: { model: StudentGroup, type: object, column: name }
    param: { module: studentGroup, action: duplicate }

freeRoom_search:
    url: /volne-miestnosti/zoznam.:sf_format
    param: { module: freeRoom, action: search, sf_format: html }
    requirements: { sf_format: (?:html|csv) }

freeRoom_search_parameters:
    url: /volne-miestnosti/parametre-vyhladavania
    param: { module: freeRoom, action: params }

lessonSearch_search:
    url: /hodiny-v-intervaloch/zoznam.:sf_format
    param: { module: lessonSearch, action: search, sf_format: html }
    requirements: { sf_format: (?:html|csv) }

lessonSearch_search_parameters:
    url: /hodiny-v-intervaloch/parametre-vyhladavania
    param: { module: lessonSearch, action: params }
    
lessonSearch_current:
    url: /aktualne
    param: { module: lessonSearch, action: current }

panel_list_lessons:
    url: /panel/list-lessons
    param: { module: panel, action: listLessons }

panel_list_teachers:
    url: /panel/list-teachers
    param: { module: panel, action: listTeachers }

panel_list_rooms:
    url: /panel/list-rooms
    param: { module: panel, action: listRooms }

panel_list_studentGroups:
    url: /panel/list-studentGroups
    param: { module: panel, action: listStudentGroups }
