# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, print.css { media: print }, tty.css { media: tty }, dark.css { title: 'Tmavé farby' }, light.css { rel: 'alternate stylesheet' title: 'Svetlé farby' }]

  javascripts:    [mootools-1.2.4-core.js, element.js, layout.js, timetable_editor.js, timetable.js, search.js]

  has_layout:     true
  layout:         layout
